Step 2. try 1
z216ero/react-burger pull request #3
Opened 2022-09-15 02:44 UTC by z216ero

2022-09-16 05:55 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Необходимо создать отдельный компонент Modal. ModalOverlay это просто подложка, у неё ничего не должно быть кроме как события onClick.
- Дописать propTypes там где их нет и там где пропущены некоторые пропсы
- Вынести Modal из App в BurgerConstructor и BurgerIngredient. 
- Типизировать содержимое `ingredient`
- Добавить проверку успешности запроса.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2022-09-16 05:55 UTC, andryxxa93 commented on src/components/App/App.jsx
>      const getIngridients = async () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-09-16 05:55 UTC, andryxxa93 commented on src/components/App/App.jsx
>      const getIngridients = async () => {
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2022-09-16 05:55 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +  ingridients: PropTypes.array,
**Необходимо исправить**
Сейчас получается, что `ingredients` может быть массивом с любым содержанием. Это не правильно. Необходимо типизировать все поля ингредиента. Так же не забудьте про `isRequired`.

2022-09-16 05:55 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +  const ingridients = Array.from(props.ingridients);
**Можно лучше**
Тут нет необходимости создавать массив, потому что `ingredients` это уже массив

2022-09-16 05:55 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +export default function BurgerConstructor(props) {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2022-09-16 05:55 UTC, andryxxa93 commented on src/components/BurgerIngredients/BurgerIngredients.js
> +                                    props.setContent(<IngredientDetails ingridient={item} />)
**Необходимо исправить**
Модальное окно желательно создать внутри `burgerIngredients` и `burgerConstructor` и рендерить его только если есть выбранные для показа данные. 
Как-то так.
```
 {ingredientInModal && (
        <Modal onClose={closeIngredientModal} title="Детали ингредиента">
          <IngredientDetails ingredientData={ingredientInModal} />
        </Modal>
      )}
```

2022-09-16 05:55 UTC, andryxxa93 commented on src/components/ModalOverlay/ModalOverlay.js
> +    const closeByClickBackgroundHanlder = (e) => {
**Необходимо исправить**
Идея с прослушивателем на бекграунд имеет право на жизнь, но в этом проекте в будущем это принесёт сложности. ModalOVerlay должен быть отдельным компонентом у которого в props передается функция закрытия срабатываемая на onClick.

2022-09-16 05:55 UTC, andryxxa93 commented on src/components/ModalOverlay/ModalOverlay.js
> +ModalOverlay.propTypes = {
**Необходимо исправить**
Тут не хватает типизации пропса `children`

2022-09-16 05:55 UTC, andryxxa93 commented on src/components/App/App.jsx
>      const getIngridients = async () => {
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2022-09-16 05:55 UTC, andryxxa93 commented on src/components/IngredientDetails/IngredientDetails.js
> +}
**Необходимо исправить**
Все компоненты с пропсами должны иметь типизацию через propTypes.

2022-09-16 05:55 UTC, andryxxa93 commented on src/components/BurgerConstructor/BurgerConstructor.js
> +  ingridients: PropTypes.array,
**Можно лучше**

во многих компонентах дублируется описание PropTypes ингредиента
Лучше вынести его в отдельный файл (можно создать файл prop-types.js в корне src) и переиспользовать описание пропсов ингрединта, а не дублировать

2022-09-16 17:05 UTC, z216ero commented on src/components/App/App.jsx
>      const getIngridients = async () => {
done

2022-09-16 17:12 UTC, z216ero commented on src/components/App/App.jsx
>      const getIngridients = async () => {
done

2022-09-16 18:08 UTC, z216ero commented on src/components/BurgerConstructor/BurgerConstructor.js
> +  ingridients: PropTypes.array,
done

2022-09-16 18:11 UTC, z216ero commented on src/components/BurgerConstructor/BurgerConstructor.js
> +  const ingridients = Array.from(props.ingridients);
done

2022-09-16 18:12 UTC, z216ero commented on src/components/BurgerConstructor/BurgerConstructor.js
> +export default function BurgerConstructor(props) {
done

2022-09-16 18:16 UTC, z216ero commented on src/components/ModalOverlay/ModalOverlay.js
> +ModalOverlay.propTypes = {
done

2022-09-17 07:49 UTC, andryxxa93 approved these changes
Вы хорошо потрудились. Ваша работа принята! Удачного продолжения обучения!

2022-09-17 20:38 UTC, merged